############################################################
##    FILENAME:   preprocess.py    
##    VERSION:    1.0
##    SINCE:      2016-02-21
##    AUTHOR: 
##        Jimmy Lin (xl5224) - JimmyLin@utexas.edu  
##
############################################################
##    Edited by MacVim
##    Documentation auto-generated by Snippet 
############################################################

import sys, os

def usage (): 
    print "This program converts raw POS format file to mallet input data file. "
    print "Usage: "
    print "\tpython preprocess.py [pos_file(directory)] [mallet_file]"

def preprocess (posFileName, malFileName, Option): 
    print "processing:", posFileName
    fout = open(malFileName, Option)
    fin = open(posFileName, "r")
    for line in fin: 
        if len(line) <= 2: continue # empty line
        if line[0] == '=' or line[2] == '@': # CD line or tagging line
            fout.write('\n')
            fout.write('\n')
            continue 
        # uniform processing of word-tag pair and pairs
        line = line.strip("\n")
        line = line.strip(" [")
        line = line.strip(" ]")
        pairs = line.split(' ')
        for p in pairs: 
            p = p.replace('/', ' ')
            fout.write(p)
            fout.write('\n')
    fout.write('\n')
    fin.close()
    fout.close()
    print "Done."

def main ():
    if len(sys.argv) != 3: 
        usage()
        sys.exit(1)
    posFileName = sys.argv[1]
    malFileName = sys.argv[2]

    # initialize an empty file (cleanup if already exist)
    os.remove(malFileName)
    if not os.path.isdir(posFileName): # posFileName is a file
        preprocess (posFileName, malFileName, "w+")
    else:  # posFileName is a directory
        for subdir, dirs, files in os.walk(posFileName):
            for file in files:
                fileToDo = os.path.join(subdir, file)
                if fileToDo.endswith(".pos"):
                    preprocess (fileToDo, malFileName, "a+")

if __name__ == '__main__':
    main()
