all:

tar:
	tar czvf CS388_HW03_XL5224.tar.gz README.txt report.pdf condor_files matlab_plots stanford-parser/BROWNPreprocessor.java stanford-parser/WSJPreprocessor.java stanford-parser/Makefile stanford-parser/MyParser.java stanford-parser/stanford-parser.jar traces

push: 
	git add README.txt Makefile condor_files report.pdf 
	git commit
	git push
