all:

tar:
	tar czvf CS388_HW03_XL5224.tar.gz README report.pdf condor_files matlab_plots stanford-parser/BROWNPreprocessor.java stanford-parser/WSJPreprocessor.java stanford-parser/Makefile stanford-parser/slf4j-api.jar stanford-parser/slf4j-simple.jar stanford-parser/stanford-parser-3.6.0-models.jar stanford-parser/stanford-parser.jar stanford-parser/MyParser.java

push: 
	git add README Makefile condor_files
	git commit
	git push
